### PR TITLE
ARXIVNG-1175 Support for ancillary uploads

### PR DESCRIPTION
**Pull request by erickpeirson**
This adds support on the submission UI to upload files as ancillary files. Instead of placing the file in the root of the upload workspace, files should be placed in the ancillary subdirectory (``anc``). This depends on https://github.com/cul-it/arxiv-filemanager/pull/20 and on https://github.com/cul-it/arxiv-submission-ui/pull/31 

image

### CODE REVIEW

**Comment by erickpeirson** [comment]
The rub here is that "just updated" is inferred from the timestamps on the files. The directories aren't represented as separate objects, they're just inferred from the paths/keys of the files. We could highlight directories that contain files that were updated, however.

**Comment by eawoods** [comment]
ohhhhh - I see. Let's not worry about highlighting the directory, then, unless it looks weird when a whole folder/group of folders gets updated and is all green except the directories.

**Comment by erickpeirson** [comment]
Bounced base to regenerate diffs. This should be ready to review

**Comment by eawoods** [comment]
Testing looks great - I tried my best to break it and it has been flawless thus far. :)

**Pull request merged**
